# Site settings
title: "geekineers"
email: developers@8layertech.com
description: > # this means to ignore newlines until "baseurl:"
  8Layer Technologies Inc. &copy 2017
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://8layertech.com" # the base hostname & protocol for your site
twitter_username: fffabs
github_username:  toxinide

# Build settings
markdown: kramdown
permalink: ":title/"
highlighter: pygments

# Pagination
paginate: 10
paginate_path: "blog/page/:num/"

# Minification
sass:
  style: compressed

future: true